version: "3"
services:
  api:
    container_name: manwha-reader-api
    build:
      context: ../backend
    command: poetry run python -m src.presentation.api.main
    restart: on-failure
    environment:
      DB_HOST: postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    container_name: manwha-reader-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    secrets:
      - postgres_password
    environment:
      POSTGRES_DB: "manwha_reader"
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

  frontend:
    build:
      network: host
      context: ../frontend
    container_name: manwha-reader-frontend
    ports:
      - 3000:3000
    depends_on:
      - api

secrets:
  postgres_password:
    file: ./postgres/secret.txt
