version: "3"
services:
  api:
    container_name: manwha-reader-api
    build:
      context: ../backend
    command: poetry run python -m src.presentation.api.main
    restart: on-failure
    volumes:
      - ./../backend/src:/var/www/manwha-reader/src
    environment:
      DB_HOST: postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    container_name: manwha-reader-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "manwha_reader"

  frontend:
    build:
      network: host
      context: ../frontend
    container_name: manwha-reader-frontend
    ports:
      - 3000:443
