name: Deploy Backend

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yaml"
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync backend repository with VPS
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete
          path: backend/
          remote_path: /var/www/manwha-reader/backend/
          remote_host: ${{ secrets.VPS_HOST }}
          remote_port: ${{ secrets.VPS_PORT }}
          remote_user: ${{ secrets.VPS_USERNAME }}
          remote_key: ${{ secrets.VPS_SSHKEY }}

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSHKEY }}
          script: |
            cd /var/www/manwha-reader/.docker
            truncate -s 0 ../backend/.env
            echo "
              DB_USER=${{ secrets.DB_USER }}
              DB_PASSWORD=${{ secrets.DB_PASSWORD }}
              DB_NAME=${{ secrets.DB_NAME }}
              AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
              AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
              AWS_REGION=${{ secrets.AWS_REGION }}
              AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
              DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}
              MANWHA_READER_URL=${{ secrets.MANWHA_READER_URL }}
            " >> ../backend/.env

            docker compose build api
            docker compose up api -d
