name: Deploy Backend

on:
  push:
    paths:
      - "backend/**"
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync backend repository with VPS
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete
          path: backend/
          remote_path: /var/www/manwha-reader/backend/
          remote_host: ${{ secrets.VPS_HOST }}
          remote_port: ${{ secrets.VPS_PORT }}
          remote_user: ${{ secrets.VPS_USERNAME }}
          remote_key: ${{ secrets.VPS_SSHKEY }}

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSHKEY }}
          script: |
            cd /var/www/manwha-reader/.docker
            truncate -s 0 .env
            printf 'API_URL=${{ secrets.API_URL }}' >> .env

            docker compose build backend
            docker compose up backend -d
