name: Frontend CI

on:
  pull_request_target:
    types: [opened, edited, closed]
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [20.11.x]
        architecture: [x64]
    steps:
      - name: Checkout to git repository
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./backend/package-lock.json

      - name: Install project dependencies
        run: npm install
      
