name: Lint Frontend

on:
  pull_request:
    paths:
      - "frontend/**"

env:
  NODE_VERSION: "20.11.x"

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout to git repository
        uses: actions/checkout@v2

      - name: Setup node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install project dependencies
        run: npm install

      - name: Run linter
        run: npm run lint
